name: Copy README from Remote Repo

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  copy-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2